# Generated by Django 2.2.5 on 2019-12-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=512)),
                ('question_type', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='enquete',
            name='enquete_id',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='enquete_name',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.Choice')),
                ('Q_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.Question')),
            ],
        ),
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.Enquete')),
                ('Q_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.Question')),
            ],
        ),
    ]
